feat: update milvus model to support jina embeddings 3
milvus-io/milvus-model pull request #38
Opened 2024-09-12 12:35 UTC by bwanglzu

This PR should allow `pymilvus` support `jina-embeddings-v3:

with 2 additional fields:

1. task_type: to properly load adapters
2. dimensions: allow user to truncate dimension with MRL.

2024-09-12 12:36 UTC, JoanFM requested changes

2024-09-12 12:36 UTC, JoanFM commented on milvus_model/dense/jinaai.py
> +        if self.model_name == "jina-embeddings-v3":
avoid doing this, just pass them if they are not None, the backend will return an error or not.

2024-09-12 14:13 UTC, wxywb commented
Is there any doc about jina v3 embedding? what kind of tasks_type it can use?

2024-09-12 14:33 UTC, bwanglzu commented
hi @wxywb yes i'm working on another PR to milvus-docs with detailed documentation, the tasks are:

```bash
+ **retrieval.query**: Used to encode user queries or questions in retrieval tasks.
+ **retrieval.passage**: Used to encode large documents in retrieval tasks at indexing time.
+ **classification**: Used to encode text for text classification tasks.
+ **text-matching**: Used to encode text for similarity matching, such as measuring similarity between two sentences.
+ **separation**: Used for clustering or reranking tasks.
```

2024-09-12 14:35 UTC, bwanglzu commented
i need to figure out a good way for this PR, now my problem is, we have a `encode_query` and `encode_document` function built-in each embedding function, such as `JinaEmbeddingFunction`, i guess in these two functions, i need to use task_type=query and task_type=passage respectively.

While for other tasks, i'm not sure what is the best way to parse this `task_type`, so i overwrite the `__call__` function (not sure if it is desired).

Can you give me some suggestions?

Bo

2024-09-12 14:37 UTC, bwanglzu commented
(btw if you are in the `jina_ai-x-milvus` joint slack channel, i can give you more detailed information :)

2024-09-12 16:39 UTC, JoanFM requested changes

2024-09-12 16:39 UTC, JoanFM commented on milvus_model/dense/jinaai.py
> +            "dimensions": self.dimensions,
please check that `self.dimensions` and `task_type` are not None before putting them in the `data`

2024-09-13 02:16 UTC, wxywb commented
The current design puts `task_type` in the __init__ method, and the __call__ method will use this setting. If someone needs to change it, they can create a new embedding function.
You can see an example in cohere.
https://github.com/milvus-io/milvus-model/blob/main/milvus_model/dense/cohere.py

2024-09-16 11:54 UTC, closed without merging